name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  stylua:
    name: StyLua
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - name: Stylua
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: v2.3.0
          args: --check lua tests

  typecheck:
    name: EmmyLuaCheck
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - name: Install EmmyLuaCheck
        uses: jaxxstorm/action-install-gh-release@v2.1.0
        with:
          repo: EmmyLuaLs/emmylua-analyzer-rust
          tag: 0.17.0
          asset-name: emmylua_check
          chmod: 0755
      - name: Install Neovim and dependencies
        run: |
          bash ./.github/workflows/install_nvim.sh
          make deps
      - name: Run check
        run: |-
          export VIMRUNTIME=$(nvim -es '+put=$VIMRUNTIME|print|quit!')
          emmylua_check --warnings-as-errors -c .emmyrc.json lua tests

  run_tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          - nvim_tag: v0.10.0
          - nvim_tag: v0.10.4
          - nvim_tag: v0.11.0
          - nvim_tag: v0.11.4
          - nvim_tag: nightly

    name: Run tests
    runs-on: ubuntu-24.04
    env:
      NVIM_TAG: ${{ matrix.nvim_tag }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0  # required to run neogit extension test - rewrite?

      - name: Install Neovim and dependencies
        run: |
          bash ./.github/workflows/install_nvim.sh
          sudo apt install fzf

      - name: Run tests
        run: |
          make test

  update_docs:
    name: Update docs
    runs-on: ubuntu-latest
    if: 'false' # TODO: skip doc generation for now, need to be rewritten
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true

      - name: Install Neovim and dependencies
        run: |
          bash ./.github/workflows/install_nvim.sh

      - name: Update docs
        run: |
          python -m pip install pyparsing==3.0.9
          make doc
      - name: Commit changes
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_MSG: |
            [docgen] Update docs
            skip-checks: true
        run: |
          git config user.email "actions@github"
          git config user.name "Github Actions"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git add README.md doc
          # Only commit and push if we have changes
          git diff --quiet && git diff --staged --quiet || (git commit -m "${COMMIT_MSG}"; git push origin HEAD:${GITHUB_REF})

  release:
    name: release
    if: 'false' # TODO: skip releasing, this is a WIP still
    needs:
      - stylua
      - typecheck
      - run_tests
      - update_docs
    runs-on: ubuntu-24.04
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: simple
      - uses: actions/checkout@v5
      - uses: rickstaa/action-create-tag@v1
        if: ${{ steps.release.outputs.release_created }}
        with:
          tag: stable
          message: "Current stable release: ${{ steps.release.outputs.tag_name }}"
          tag_exists_error: false
          force_push_tag: true
